//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2_GRUPO_21
{
    public partial class Ejercicio1
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.TextBox txtProducto1;
        protected global::System.Web.UI.WebControls.TextBox txtCantidad1;
        protected global::System.Web.UI.WebControls.TextBox txtProducto2;
        protected global::System.Web.UI.WebControls.TextBox txtCantidad2;
        protected global::System.Web.UI.WebControls.Button btnGenerar;
        protected global::System.Web.UI.WebControls.Label lblTabla;
    }
}